version: '3.7'

services:
  db:
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cvService
    image: postgres:latest
    networks:
      - cvService

  cvService:
    container_name: project
    image: krreww/krainettestproject:version3
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - cvService

networks:
  cvService:
    driver: bridge


